/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package f1;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.java_websocket.drafts.Draft_10;
import java.util.ArrayList;
import java.util.List;
import org.java_websocket.drafts.Draft_76;
import org.json.simple.JSONObject;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.*;
import org.w3c.dom.*;
import org.xml.sax.*;
import javax.xml.transform.*;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.parsers.DocumentBuilder;
import org.java_websocket.drafts.Draft_17;

/**
 *
 * @author dario
 */
public class Start extends javax.swing.JFrame {

    public enum StatoGara {ATTESA_CARICAMENTO,ATTESA_AVVIO,GARA_AVVIO};
    Boolean chiusura=false;
    StatoGara stato= StatoGara.ATTESA_CARICAMENTO;
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
String webserverUrl = "";
try{
Properties prop = new Properties();
prop.load(new FileInputStream("config.properties"));
webserverUrl = prop.getProperty("webserver");
}catch(IOException ex){
 ex.printStackTrace();
}
        try {
            c = new websocket(new URI(webserverUrl), new Draft_17(),this); // more about drafts here: http://github.com/TooTallNate/Java-WebSocket/wiki/Drafts
            //se usi draft_75 o 76 nn va la send c'è un issue aperta: https://github.com/TooTallNate/Java-WebSocket/issues/144
            c.connect();
            cambiaStatoGara(StatoGara.ATTESA_CARICAMENTO);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
            jLabel3.setText("Stato: Errore di connessione riavviare il programma");

        }
    }

    public void cambiaStatoGara(StatoGara s){
        switch(s){
          case ATTESA_CARICAMENTO:
            stato=StatoGara.ATTESA_CARICAMENTO;
            jButton3.setEnabled(true);
            jButton1.setEnabled(true);
            jButton4.setEnabled(false);
            SetStato("Stato: Gara in Attesa di caricamento");
            break;
          case ATTESA_AVVIO:
            stato=StatoGara.ATTESA_AVVIO;
            jButton3.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(true);
            SetStato("Stato: Gara in Attesa di avvio");
            break;
          case GARA_AVVIO:
            stato=StatoGara.GARA_AVVIO;
            jButton3.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            SetStato("Stato: Gara in avviamento...");

            break;
          
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formula 1");
        setBackground(new java.awt.Color(244, 244, 244));
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 3, 36)); // NOI18N
        jLabel1.setText("Progetto SCD - Formula 1");

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("sfoglia");
        jButton3.setName("jbChose"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChoseAP(evt);
            }
        });

        jLabel2.setText("File xml con le informazioni del circuito corrente:");
        jLabel2.setName("JLChose"); // NOI18N

        jLabel3.setText("Stato: Non Connesso");
        jLabel3.setFocusable(false);
        jLabel3.setName("JLStatus"); // NOI18N

        jButton4.setText("Avvia");
        jButton4.setMaximumSize(new java.awt.Dimension(50, 27));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 27));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Avvio(evt);
            }
        });

        jButton1.setText("Chiudi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminaProgramma(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jbChoseAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChoseAP
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser("../..");
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter("xml files (*.xml)", "xml");
        fc.setFileFilter(xmlfilter);
        fc.setDialogTitle("Apri il file xml della pista");
        
        // set selected filter
        fc.setFileFilter(xmlfilter);

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            f = fc.getSelectedFile();
            jTextField1.setText(f.getPath());
        }
        
         try {

            
           

            JSONObject obj = new JSONObject();
            obj.put("tipo", 1);

            /*DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document doc = builder.parse(f.getPath());
            StringWriter stringWriter = new StringWriter();
            Transformer transformer = TransformerFactory.newInstance().newTransformer();
            transformer.transform(new DOMSource(doc), new StreamResult(stringWriter));
            String strFileContent = stringWriter.toString(); //This is string data of xml file
            obj.put("pista", strFileContent);
*/
            BufferedReader br = new BufferedReader(new FileReader(f));
            String line;
            StringBuilder sb = new StringBuilder();

            while((line=br.readLine())!= null){
                sb.append(line.trim());
            }
            obj.put("pista", sb.toString());

            c.send(obj.toString().replace("\\/", "/"));

            cambiaStatoGara(StatoGara.ATTESA_AVVIO);

       /* } catch (URISyntaxException e) {
            System.out.println("Errore: " + e.getMessage());
        } catch (TransformerException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);*/
        } catch (IOException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbChoseAP

    private void Avvio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Avvio

        JSONObject obj = new JSONObject();
        obj.put("tipo", 2);
//            System.out.print(obj.toString());

        c.send(obj.toString());
        cambiaStatoGara(StatoGara.GARA_AVVIO);
        
    }//GEN-LAST:event_Avvio

    private void terminaProgramma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminaProgramma
        // TODO add your handling code here:
        termina();
    }//GEN-LAST:event_terminaProgramma

    private void termina(){
        chiusura=true;
        JSONObject obj = new JSONObject();
        obj.put("tipo", 3);
  //      System.out.print(obj.toString());

        c.send(obj.toString());
        
        c.close();
        
//        java.lang.System.exit(0);
        dispose();
    
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        termina();
    }//GEN-LAST:event_formWindowClosing

    public void SetStato(String sStato){
        jLabel3.setText(sStato);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private websocket c = null;
    private File f;
}
